package chat

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"path/filepath"
	"regexp"
	"strings"
	"sync"
	"time"

	"github.com/langPeanut/langPeanut/pkg/agents"
	"github.com/langPeanut/langPeanut/pkg/llm"
	"github.com/langPeanut/langPeanut/pkg/memory"
	"github.com/langPeanut/langPeanut/pkg/platforms"
	"github.com/langPeanut/langPeanut/pkg/types"
)

// LLMPlanResult represents the autonomous tool calling and reasoning decision from the LLM
type LLMPlanResult struct {
	Thought        string        `json:"thought"`
	ToolCalls      []LLMToolCall `json:"tool_calls"`
	DirectResponse string        `json:"direct_response,omitempty"`
}

// LLMToolCall represents a single tool invocation generated by the LLM
type LLMToolCall struct {
	Name      string         `json:"name"`
	Arguments map[string]any `json:"arguments"`
}

// Engine is the central multi-turn conversational orchestrator
type Engine struct {
	mu               sync.RWMutex
	ProjectRoot      string
	Platform         platforms.Platform
	LLMClient        llm.Client
	Tools            *ToolRegistry
	History          []ChatMessage
	Candidates       []types.StringCandidate
	RefactorPlans    map[string]*types.FileRefactorPlan
	LastResult       *agents.PipelineResult
	SourceLocale     string
	TargetLocales    []string
	ToneStyle        string
	RepoMetadata     map[string]any
	MissingConfig    []string
	JobTriggerHook   func(ctx context.Context, branch, directive string) (map[string]any, error)
	JobsQueryHook    func(ctx context.Context, limit int) ([]map[string]any, error)
	ConfigUpdateHook func(ctx context.Context, updates map[string]any) (map[string]any, error)
	MatrixUpdateHook func(ctx context.Context, matrix map[string]map[string]string) error
	KeyUpdateHook    func(ctx context.Context, locale, key, value string) error
}

// NewEngine initializes the Central Agentic Chat Engine
func NewEngine(projectRoot string, client llm.Client) (*Engine, error) {
	absRoot, err := filepath.Abs(projectRoot)
	if err != nil {
		absRoot = projectRoot
	}

	registry := platforms.NewRegistry()
	platform, _ := registry.AutoDetect(absRoot)
	if platform == nil {
		platform, _ = registry.Get(types.FrameworkGeneric)
	}

	if client == nil {
		cfg := memory.LoadConfig(absRoot)
		provider := llm.ProviderClaude
		model := "claude-sonnet-5"
		if cfg != nil {
			if cfg.ActiveProvider != "" {
				provider = llm.ProviderType(cfg.ActiveProvider)
			}
			if cfg.ActiveModel != "" {
				model = cfg.ActiveModel
			}
		}
		client = llm.NewClient(provider, model)
	}

	engine := &Engine{
		ProjectRoot:   absRoot,
		Platform:      platform,
		LLMClient:     client,
		Tools:         NewToolRegistry(),
		History:       make([]ChatMessage, 0),
		Candidates:    make([]types.StringCandidate, 0),
		RefactorPlans: make(map[string]*types.FileRefactorPlan),
		SourceLocale:  "en",
		TargetLocales: []string{"es", "fr", "de", "ja"},
		ToneStyle:     "default",
	}
	return engine, nil
}

// SendMessage processes user input, manages tool calling, and streams events
func (e *Engine) SendMessage(ctx context.Context, userText string, eventChan chan<- ChatEvent) (*ChatMessage, error) {
	e.mu.Lock()
	defer e.mu.Unlock()

	userMsg := ChatMessage{
		ID:        generateID("id"),
		Role:      RoleUser,
		Content:   userText,
		Timestamp: time.Now(),
	}
	e.History = append(e.History, userMsg)

	var toolCalls []ToolCall
	var planThought string
	var directResp string

	// Step 1: Autonomous LLM Tool Planning (LLM is in full control)
	if e.LLMClient != nil {
		plan, err := e.planWithLLM(ctx, userText)
		if err == nil && plan != nil {
			planThought = plan.Thought
			if planThought != "" {
				emitEvent(eventChan, ChatEvent{
					Type:    "thought",
					Content: planThought,
				})
			}
			for _, tc := range plan.ToolCalls {
				toolCalls = append(toolCalls, ToolCall{
					ID:        generateID("tc"),
					Name:      tc.Name,
					Arguments: tc.Arguments,
				})
			}
			directResp = plan.DirectResponse
		}
	}

	// Fallback intent detection if LLM planning had no tool calls and no direct response (e.g. offline mode)
	if len(toolCalls) == 0 && directResp == "" {
		toolCalls = e.detectToolCallsFallback(userText)
	}

	var toolResults []ToolResult
	var generatedCards []UICard
	var thoughts []string
	if planThought != "" {
		thoughts = append(thoughts, planThought)
	}

	// Step 2: Execute tool calls
	for _, tc := range toolCalls {
		emitEvent(eventChan, ChatEvent{
			Type:     "tool_start",
			ToolCall: &tc,
			Content:  fmt.Sprintf("Executing %s...", tc.Name),
		})

		toolDef, exists := e.Tools.Get(tc.Name)
		if !exists {
			continue
		}

		out, card, err := toolDef.Handler(ctx, tc.Arguments, e)
		isErr := err != nil
		errMsg := ""
		if isErr {
			errMsg = err.Error()
		}

		tr := ToolResult{
			ToolCallID: tc.ID,
			Name:       tc.Name,
			Output:     out,
			Error:      errMsg,
			IsError:    isErr,
		}
		toolResults = append(toolResults, tr)

		if card != nil {
			generatedCards = append(generatedCards, *card)
			emitEvent(eventChan, ChatEvent{
				Type: "card",
				Card: card,
			})
		}

		emitEvent(eventChan, ChatEvent{
			Type:       "tool_end",
			ToolCall:   &tc,
			ToolResult: &tr,
		})
	}

	// Step 3: Synthesize final assistant response
	var responseText string
	if len(toolCalls) > 0 || directResp == "" {
		responseText = e.synthesizeResponse(ctx, userText, toolCalls, toolResults, thoughts)
	} else {
		responseText = directResp
	}

	// Stream text chunks
	if eventChan != nil {
		words := strings.Fields(responseText)
		for _, w := range words {
			emitEvent(eventChan, ChatEvent{
				Type:    "chunk",
				Content: w + " ",
			})
		}
	}

	assistantMsg := ChatMessage{
		ID:          generateID("id"),
		Role:        RoleAssistant,
		Content:     responseText,
		Timestamp:   time.Now(),
		ToolCalls:   toolCalls,
		ToolResults: toolResults,
		Cards:       generatedCards,
	}
	e.History = append(e.History, assistantMsg)

	emitEvent(eventChan, ChatEvent{
		Type:    "done",
		Content: responseText,
	})

	return &assistantMsg, nil
}

func (e *Engine) planWithLLM(ctx context.Context, userPrompt string) (*LLMPlanResult, error) {
	toolSchemas := e.Tools.GetDefinitionsSchema()
	schemaBytes, err := json.MarshalIndent(toolSchemas, "", "  ")
	if err != nil {
		return nil, err
	}

	var repoDetailsSb strings.Builder
	if len(e.RepoMetadata) > 0 {
		repoDetailsSb.WriteString("• Live Platform Repository Metadata:\n")
		for k, v := range e.RepoMetadata {
			repoDetailsSb.WriteString(fmt.Sprintf("  - %s: %v\n", k, v))
		}
	}
	if len(e.MissingConfig) > 0 {
		repoDetailsSb.WriteString("• Detected Platform Configuration Gaps & Missing Items:\n")
		for _, m := range e.MissingConfig {
			repoDetailsSb.WriteString(fmt.Sprintf("  - [ACTION REQUIRED] %s\n", m))
		}
	}

	systemPrompt := fmt.Sprintf(`You are the autonomous Central Agentic Copilot and Multi-Agent Orchestrator for langPeanut.
Your mission is to understand the developer's instructions, maintain deep memory of their directives and preferences across the entire conversation, and autonomously plan and execute tools to manage internationalization, code refactoring, ICU safety, SEO, and platform jobs.

MULTI-AGENT SYSTEM ARCHITECTURE & CAPABILITIES:
1. AST Scout & Parser: Tree-sitter powered parser for Dart/Flutter, TypeScript/React/Next.js, SwiftUI, Kotlin Jetpack Compose, Vue, Angular, Python, and Go. Extracts hardcoded UI strings with zero regex flaws.
2. Context Disambiguation Agent: Classifies strings into UI categories (button, header, toast, dialog), extracts ICU variable placeholders ({userName}, {count}), and infers plural forms.
3. Cultural Translator Agent: Translates keys into target locales with tone adherence (casual, formal, technical, gen_z), regional idioms, and brand glossary protection.
4. 4-Tier Verifier Critic: Quality gate validating AST syntax (Tier 1), ICU placeholder token alignment (Tier 2), layout expansion constraints (Tier 3), and key parity deltas (Tier 4).
5. AST Patch Engine: Applies deterministic byte-range replacements and creates atomic rollback checkpoints.
6. Global SEO Agent: Simulates Google SERP previews (600px desktop/mobile) and weaves high-intent regional keywords.
7. Platform Execution Engine: Queues asynchronous cloud jobs on Git branches, updates repository settings, and synchronizes translation matrix catalogs.

WORKSPACE CONTEXT:
• Project: %s
• Framework: %s
• Discovered Hardcoded Strings: %d
• Target Locales: %v
• Tone Setting: %s
%s

AVAILABLE TOOLS:
%s

OUTPUT SPECIFICATION:
Return a strictly valid JSON object matching:
{
  "thought": "Your internal chain-of-thought explaining the user's intent, remembered preferences from past turns, and tool selection rationale (NO EMOJIS)",
  "tool_calls": [
    {
      "name": "tool_name",
      "arguments": { ... }
    }
  ],
  "direct_response": "Optional direct response if no tool call is needed (NO EMOJIS)"
}

OPERATING RULES:
1. REMEMBER CONVERSATION CONTEXT: Adhere to directives given in earlier turns (e.g. if the user previously specified locales 'es, ja' or tone 'casual', persist those preferences in subsequent tool calls).
2. AUTONOMOUS TOOL INVOCATION:
   - When the user asks to trigger/run/queue a job or start the pipeline, call "trigger_job" with branch and directive arguments.
   - When the user asks to view past jobs or PR status, call "query_jobs".
   - When the user asks to edit or correct a specific key, call "update_translation_key".
   - When the user asks to scan, inspect, or audit the repository, call "scan_repository".
   - When the user asks to translate or localize, call "execute_localization" or "plan_localization".
   - When the user asks to verify or check ICU safety, call "verify_translations".
   - When the user asks to change settings, target locales, or tone, call "manage_config".
   - When the user asks to undo or view snapshots, call "manage_checkpoints".
   - When the user asks for SEO or SERP simulations, call "seo_simulate_serp" or "seo_weave_copy".
   - When the user asks to analyze brand tone or glossary, call "scout_personas".
   - When the user asks to clean unused keys, call "prune_dead_keys".
   - When the user asks to test health/parsers/keys, call "diagnose_system".
3. DIRECT RESPONSES & GAP REPORTING: If the user asks about repository settings, setup status, what is configured, or what is missing, give a detailed direct_response synthesizing the workspace context and detected gaps.
4. NO EMOJIS: Never include emojis in thoughts or direct responses.
5. Strict JSON only with no markdown backticks.`,
		filepath.Base(e.ProjectRoot),
		e.Platform.DisplayName(),
		len(e.Candidates),
		e.TargetLocales,
		e.ToneStyle,
		repoDetailsSb.String(),
		string(schemaBytes),
	)

	var historySb strings.Builder
	if len(e.History) > 1 {
		startIdx := 0
		if len(e.History) > 20 {
			startIdx = len(e.History) - 20
		}
		for i := startIdx; i < len(e.History)-1; i++ {
			msg := e.History[i]
			historySb.WriteString(fmt.Sprintf("%s: %s\n", msg.Role, msg.Content))
		}
	}

	userMsg := fmt.Sprintf("Conversation History:\n%s\nUser Request: %s", historySb.String(), userPrompt)
	raw, err := e.LLMClient.Complete(ctx, systemPrompt, userMsg)
	if err != nil {
		return nil, err
	}

	raw = cleanJSONResponse(raw)
	var plan LLMPlanResult
	if err := json.Unmarshal([]byte(raw), &plan); err != nil {
		return nil, err
	}
	return &plan, nil
}

func cleanJSONResponse(s string) string {
	s = strings.TrimSpace(s)
	if strings.HasPrefix(s, "```json") {
		s = strings.TrimPrefix(s, "```json")
	} else if strings.HasPrefix(s, "```") {
		s = strings.TrimPrefix(s, "```")
	}
	s = strings.TrimSuffix(s, "```")
	return strings.TrimSpace(s)
}

// detectToolCallsFallback matches user prompt with tools as an offline backup
func (e *Engine) detectToolCallsFallback(userPrompt string) []ToolCall {
	var toolCalls []ToolCall
	p := strings.ToLower(userPrompt)

	// Intent 0: Trigger Platform Job / Background Run
	if strings.Contains(p, "trigger") || strings.Contains(p, "queue job") || strings.Contains(p, "run job") || strings.Contains(p, "start job") || strings.Contains(p, "the job") || strings.Contains(p, "start pipeline") {
		branch := "main"
		if strings.Contains(p, "branch") {
			parts := strings.Fields(p)
			for i, word := range parts {
				if word == "branch" && i+1 < len(parts) {
					branch = strings.Trim(parts[i+1], `"'.,`)
				}
			}
		}
		toolCalls = append(toolCalls, ToolCall{
			ID:        generateID("id"),
			Name:      "trigger_job",
			Arguments: map[string]any{"branch": branch, "directive": userPrompt},
		})
		return toolCalls
	}

	// Intent 0.5: Query Platform Jobs
	if strings.Contains(p, "list jobs") || strings.Contains(p, "recent jobs") || strings.Contains(p, "job status") || strings.Contains(p, "history") || strings.Contains(p, "show jobs") {
		toolCalls = append(toolCalls, ToolCall{
			ID:        generateID("id"),
			Name:      "query_jobs",
			Arguments: map[string]any{"limit": 5},
		})
		return toolCalls
	}

	// Intent 1: Scan / Audit / Inspect
	if strings.Contains(p, "scan") || strings.Contains(p, "audit") || strings.Contains(p, "coverage") || strings.Contains(p, "matrix") || strings.Contains(p, "check repo") {
		toolCalls = append(toolCalls, ToolCall{
			ID:        generateID("id"),
			Name:      "scan_repository",
			Arguments: map[string]any{"path": e.ProjectRoot},
		})
	}

	// Intent 2: Translation / Localization
	if strings.Contains(p, "translate") || strings.Contains(p, "localiz") || strings.Contains(p, "i18n") {
		locales := extractLocalesFromPrompt(userPrompt)
		if len(locales) == 0 {
			locales = e.TargetLocales
		}
		dryRun := strings.Contains(p, "dry run") || strings.Contains(p, "preview") || strings.Contains(p, "plan")
		tone := "default"
		if strings.Contains(p, "casual") {
			tone = "casual"
		} else if strings.Contains(p, "formal") {
			tone = "formal"
		} else if strings.Contains(p, "gen-z") || strings.Contains(p, "genz") {
			tone = "gen_z"
		}

		if dryRun {
			toolCalls = append(toolCalls, ToolCall{
				ID:        generateID("id"),
				Name:      "plan_localization",
				Arguments: map[string]any{"locales": locales, "tone": tone},
			})
		} else {
			toolCalls = append(toolCalls, ToolCall{
				ID:        generateID("id"),
				Name:      "execute_localization",
				Arguments: map[string]any{"locales": locales, "tone": tone, "dry_run": false},
			})
		}
	}

	// Intent 3: Verification / Critic
	if strings.Contains(p, "verify") || strings.Contains(p, "critic") || strings.Contains(p, "test icu") || strings.Contains(p, "health check") {
		toolCalls = append(toolCalls, ToolCall{
			ID:        generateID("id"),
			Name:      "verify_translations",
			Arguments: map[string]any{},
		})
	}

	// Intent 4: SEO / Competitor Analysis / SERP
	if strings.Contains(p, "seo") || strings.Contains(p, "competitor") || strings.Contains(p, "serp") || strings.Contains(p, "keyword") {
		if strings.Contains(p, "http") {
			// Extract URL
			r := regexp.MustCompile(`https?://[^\s]+`)
			url := r.FindString(userPrompt)
			toolCalls = append(toolCalls, ToolCall{
				ID:        generateID("id"),
				Name:      "seo_analyze_competitor",
				Arguments: map[string]any{"url": url, "locale": "ja"},
			})
		} else {
			toolCalls = append(toolCalls, ToolCall{
				ID:   generateID("id"),
				Name: "seo_simulate_serp",
				Arguments: map[string]any{
					"locale":      "ja",
					"keyword":     "開発者向けローカライゼーション",
					"title":       "langPeanut ｜ 開発者向け次世代ローカライゼーションツール",
					"description": "コード内のハードコードされたテキストを自動抽出し、ICU変数とレイアウトを保護しながら自動翻訳。",
				},
			})
		}
	}

	// Intent 5: Rollback / Undo / Checkpoint
	if strings.Contains(p, "rollback") || strings.Contains(p, "undo") || strings.Contains(p, "checkpoint") || strings.Contains(p, "revert") {
		action := "list"
		if strings.Contains(p, "restore") || strings.Contains(p, "rollback") || strings.Contains(p, "undo") || strings.Contains(p, "revert") {
			action = "restore"
		}
		toolCalls = append(toolCalls, ToolCall{
			ID:        generateID("id"),
			Name:      "manage_checkpoints",
			Arguments: map[string]any{"action": action},
		})
	}

	// Intent 6: Config / Model / Tone / Locales / Directives / Settings
	isConfigIntent := strings.Contains(p, "config") || strings.Contains(p, "setting") ||
		strings.Contains(p, "switch model") || strings.Contains(p, "change model") || strings.Contains(p, "use model") ||
		strings.Contains(p, "switch provider") || strings.Contains(p, "change provider") || strings.Contains(p, "use provider") ||
		strings.Contains(p, "change tone") || strings.Contains(p, "set tone") || strings.Contains(p, "switch tone") ||
		strings.Contains(p, "set target locales") || strings.Contains(p, "add locale") || strings.Contains(p, "set locales") ||
		strings.Contains(p, "set build command") || strings.Contains(p, "set install command") || strings.Contains(p, "set root dir") ||
		strings.Contains(p, "set directive") || strings.Contains(p, "add directive") ||
		strings.Contains(p, "concurrency") || strings.Contains(p, "token limit") || strings.Contains(p, "word budget")

	if isConfigIntent {
		cfgArgs := map[string]any{"action": "get"}
		isUpdate := false

		// Detect Provider updates
		if strings.Contains(p, "claude") || strings.Contains(p, "anthropic") {
			cfgArgs["provider"] = "claude"
			isUpdate = true
		} else if strings.Contains(p, "openai") || strings.Contains(p, "gpt") {
			cfgArgs["provider"] = "openai"
			isUpdate = true
		} else if strings.Contains(p, "gemini") || strings.Contains(p, "google") {
			cfgArgs["provider"] = "gemini"
			isUpdate = true
		} else if strings.Contains(p, "ollama") || strings.Contains(p, "local model") {
			cfgArgs["provider"] = "ollama"
			isUpdate = true
		} else if strings.Contains(p, "deepl") {
			cfgArgs["provider"] = "deepl"
			isUpdate = true
		}

		// Detect Model updates
		if strings.Contains(p, "claude-sonnet-5") || strings.Contains(p, "sonnet") {
			cfgArgs["model"] = "claude-sonnet-5"
			cfgArgs["provider"] = "claude"
			isUpdate = true
		} else if strings.Contains(p, "gpt-5.4-mini") || strings.Contains(p, "gpt-4") || strings.Contains(p, "gpt-5") {
			cfgArgs["model"] = "gpt-5.4-mini"
			cfgArgs["provider"] = "openai"
			isUpdate = true
		} else if strings.Contains(p, "gemini-3.5-flash") || strings.Contains(p, "gemini-3.7") || strings.Contains(p, "gemini-flash") {
			cfgArgs["model"] = "gemini-3.5-flash"
			cfgArgs["provider"] = "gemini"
			isUpdate = true
		}

		// Detect Tone updates
		if strings.Contains(p, "tone to casual") || strings.Contains(p, "casual tone") || strings.Contains(p, "friendly tone") {
			cfgArgs["tone"] = "casual"
			isUpdate = true
		} else if strings.Contains(p, "tone to formal") || strings.Contains(p, "formal tone") || strings.Contains(p, "corporate tone") {
			cfgArgs["tone"] = "formal"
			isUpdate = true
		} else if strings.Contains(p, "tone to gen-z") || strings.Contains(p, "gen-z tone") || strings.Contains(p, "genz tone") {
			cfgArgs["tone"] = "gen_z"
			isUpdate = true
		} else if strings.Contains(p, "tone to pirate") || strings.Contains(p, "pirate tone") {
			cfgArgs["tone"] = "pirate"
			isUpdate = true
		} else if strings.Contains(p, "tone to default") || strings.Contains(p, "reset tone") {
			cfgArgs["tone"] = "default"
			isUpdate = true
		}

		// Detect Target Locales updates
		if strings.Contains(p, "locale") || strings.Contains(p, "language") {
			parsedLocs := extractLocalesFromPrompt(userPrompt)
			if len(parsedLocs) > 0 {
				cfgArgs["locales"] = parsedLocs
				isUpdate = true
			}
		}

		// Detect Root Dir updates
		if strings.Contains(p, "root dir") || strings.Contains(p, "root directory") {
			parts := strings.Fields(userPrompt)
			for i, word := range parts {
				if (strings.EqualFold(word, "dir") || strings.EqualFold(word, "directory") || strings.EqualFold(word, "to")) && i+1 < len(parts) {
					targetPath := strings.Trim(parts[i+1], "\"'`")
					if targetPath != "" && !strings.Contains(targetPath, " ") {
						cfgArgs["root_dir"] = targetPath
						isUpdate = true
						break
					}
				}
			}
		}

		// Detect Custom Build/Install Cmd updates
		if strings.Contains(p, "build cmd") || strings.Contains(p, "build command") {
			if idx := strings.Index(userPrompt, "to "); idx != -1 {
				cfgArgs["custom_build_cmd"] = strings.TrimSpace(userPrompt[idx+3:])
				isUpdate = true
			}
		}

		// Detect Custom Directive
		if strings.Contains(p, "directive") || strings.Contains(p, "instruction") {
			if idx := strings.Index(userPrompt, ":"); idx != -1 {
				cfgArgs["user_directive"] = strings.TrimSpace(userPrompt[idx+1:])
				isUpdate = true
			}
		}

		if isUpdate {
			cfgArgs["action"] = "update"
		}

		toolCalls = append(toolCalls, ToolCall{
			ID:        generateID("id"),
			Name:      "manage_config",
			Arguments: cfgArgs,
		})
	}

	// Intent 7: Doctor / Diagnostics
	if strings.Contains(p, "doctor") || strings.Contains(p, "diagnos") || strings.Contains(p, "api key") || strings.Contains(p, "health check") {
		toolCalls = append(toolCalls, ToolCall{
			ID:        generateID("id"),
			Name:      "diagnose_system",
			Arguments: map[string]any{},
		})
	}

	// Intent 8: Inspect specific string
	if strings.Contains(p, "inspect") || strings.Contains(p, "where is") || strings.Contains(p, "find string") {
		query := strings.TrimSpace(strings.ReplaceAll(strings.ReplaceAll(p, "inspect", ""), "string", ""))
		if query != "" {
			toolCalls = append(toolCalls, ToolCall{
				ID:        generateID("id"),
				Name:      "inspect_string_context",
				Arguments: map[string]any{"key_or_text": query},
			})
		}
	}

	// Intent 9: Persona Scout
	if strings.Contains(p, "persona") || strings.Contains(p, "brand voice") || strings.Contains(p, "brand tone") || strings.Contains(p, "scout brand") {
		toolCalls = append(toolCalls, ToolCall{
			ID:        generateID("id"),
			Name:      "scout_personas",
			Arguments: map[string]any{},
		})
	}

	// Intent 10: Dead Key Pruning
	if strings.Contains(p, "prune") || strings.Contains(p, "dead key") || strings.Contains(p, "unused key") || strings.Contains(p, "clean key") {
		pruneMode := strings.Contains(p, "delete") || strings.Contains(p, "remove") || strings.Contains(p, "prune now")
		toolCalls = append(toolCalls, ToolCall{
			ID:        generateID("id"),
			Name:      "prune_dead_keys",
			Arguments: map[string]any{"prune": pruneMode},
		})
	}

	return toolCalls
}

// synthesizeResponse crafts the assistant natural language response
func (e *Engine) synthesizeResponse(ctx context.Context, userPrompt string, toolCalls []ToolCall, toolResults []ToolResult, thoughts []string) string {
	if e.LLMClient != nil {
		existingLocales := []string{}
		if e.Platform != nil {
			if locMap, err := e.Platform.DiscoverExistingLocales(e.ProjectRoot); err == nil {
				for loc := range locMap {
					existingLocales = append(existingLocales, loc)
				}
			}
		}

		var repoDetailsSb strings.Builder
		if len(e.RepoMetadata) > 0 {
			repoDetailsSb.WriteString("• Live Platform Repository Metadata:\n")
			for k, v := range e.RepoMetadata {
				repoDetailsSb.WriteString(fmt.Sprintf("  - %s: %v\n", k, v))
			}
		}
		if len(e.MissingConfig) > 0 {
			repoDetailsSb.WriteString("• Detected Platform Configuration Gaps & Missing Items:\n")
			for _, m := range e.MissingConfig {
				repoDetailsSb.WriteString(fmt.Sprintf("  - [ACTION REQUIRED] %s\n", m))
			}
		}

		systemPrompt := fmt.Sprintf(`You are langPeanut Copilot, an elite autonomous AI software localization & growth engineering partner.
You pair-program with developers to scale their applications worldwide with zero-defect Tree-sitter AST refactoring, strict ICU placeholder protection, 4-tier critic verification, and regional SEO simulations.

MULTI-AGENT CAPABILITIES YOU ORCHESTRATE:
- AST Scout & Patch Engine: Extracts UI string candidates and applies byte-range code refactoring safely.
- Context Agent: Disambiguates semantic context, ICU placeholders, and plural structures.
- Cultural Translator: Produces culturally authentic, idiomatic translations in any requested tone.
- 4-Tier Critic: Verifies syntax, token alignment, layout expansion limits, and key parity.
- SEO Agent: Generates 600px desktop/mobile Google SERP previews and weaves high-intent keywords.
- Cloud Runner: Triggers asynchronous background localization jobs and updates repository catalogs.

WORKSPACE CONTEXT:
• Workspace Root: %s
• Detected Framework: %s
• Existing Locale Files Found: %v
• Extracted AST String Candidates: %d
• Target Locales: %v
• Tone Setting: %s
%s

HOW YOU ENGAGE:
1. Act as a thoughtful, collaborative senior developer who remembers all user directives, questions, and preferences from past conversation turns.
2. Acknowledge and build upon previous statements and decisions made by the user.
3. If the user asks about repository settings, setup status, or what is missing, give a detailed direct answer explaining what is configured and what is missing.
4. Clearly summarize tool execution results, emphasizing key findings, safety checks, and actionable next steps.
5. Format responses in clean GitHub-flavored Markdown with bullet points and code blocks.
6. NEVER use emojis in your responses.`,
			filepath.Base(e.ProjectRoot),
			e.Platform.DisplayName(),
			existingLocales,
			len(e.Candidates),
			e.TargetLocales,
			e.ToneStyle,
			repoDetailsSb.String(),
		)

		var contextSb strings.Builder

		// Inject recent multi-turn conversation history
		if len(e.History) > 1 {
			contextSb.WriteString("Conversation History:\n")
			startIdx := 0
			if len(e.History) > 20 {
				startIdx = len(e.History) - 20
			}
			for i := startIdx; i < len(e.History)-1; i++ {
				msg := e.History[i]
				role := "User"
				if msg.Role == RoleAssistant {
					role = "Assistant"
				}
				contextSb.WriteString(fmt.Sprintf("%s: %s\n", role, msg.Content))
			}
			contextSb.WriteString("\n")
		}

		if len(toolResults) > 0 {
			contextSb.WriteString("Tools Executed In This Turn:\n")
			for _, tr := range toolResults {
				if tr.IsError {
					contextSb.WriteString(fmt.Sprintf("- %s: Failed with error: %s\n", tr.Name, tr.Error))
				} else {
					contextSb.WriteString(fmt.Sprintf("- %s: Output: %v\n", tr.Name, tr.Output))
				}
			}
			contextSb.WriteString("\n")
		}

		userMessageWithContext := fmt.Sprintf("%sUser Message: %s", contextSb.String(), userPrompt)
		resp, err := e.LLMClient.Complete(ctx, systemPrompt, userMessageWithContext)
		if err == nil && strings.TrimSpace(resp) != "" {
			return strings.TrimSpace(resp)
		}
	}

	if len(toolCalls) == 0 {
		return e.generateHumanOfflineResponse(userPrompt)
	}

	var sb strings.Builder
	for _, tr := range toolResults {
		if tr.IsError {
			sb.WriteString(fmt.Sprintf("**%s encountered an issue**: %s\n\n", tr.Name, tr.Error))
			continue
		}

		switch tr.Name {
		case "trigger_job":
			sb.WriteString("**Platform localization job queued successfully.** The background worker runner has been dispatched to execute AST extraction, translation agents, ICU verification, and commit/PR creation.")
		case "query_jobs":
			sb.WriteString("Here are your recent platform localization jobs. Check the list above for job IDs, branch names, and generated GitHub Pull Request URLs.")
		case "update_translation_key":
			sb.WriteString("**Translation key updated.** The value has been saved to the active translation catalog and synced with the platform database.")
		case "scan_repository":
			sb.WriteString(fmt.Sprintf("I scanned your project (%s). Found %d hardcoded string candidates across your codebase. See the Locale Coverage Matrix above for translation completeness across your target markets.", e.Platform.DisplayName(), len(e.Candidates)))
		case "plan_localization":
			sb.WriteString("I calculated your localization execution plan. Total token estimate and pricing breakdown have been generated above. Ready to execute whenever you are ready.")
		case "execute_localization":
			sb.WriteString("**Localization pipeline completed successfully.** All missing keys were translated, verified with 100% ICU variable parity, and deterministic AST code patches have been applied. A safety checkpoint was created.")
		case "verify_translations":
			sb.WriteString("**4-Tier Critic Verification completed.** Checked AST syntax, ICU variable parity, layout expansion risk, and key integrity. Check the scorecard above for full tier results.")
		case "seo_analyze_competitor", "seo_simulate_serp":
			sb.WriteString("**SEO Simulation generated.** High-intent keywords and 600px desktop/mobile SERP previews have been rendered above.")
		case "scout_personas":
			sb.WriteString("**Brand Persona & Audience Intelligence generated.** Recommended locales, brand voice, and glossary terms have been inferred.")
		case "prune_dead_keys":
			sb.WriteString("**Dead Key Analysis completed.** Checked active in-code references against locale dictionaries.")
		case "manage_checkpoints":
			sb.WriteString("Checkpoint management action executed. Your codebase snapshots and rollback history are displayed above.")
		case "manage_config":
			sb.WriteString("System configuration and provider settings updated. Active settings are displayed in the card above.")
		case "diagnose_system":
			sb.WriteString("System diagnostics completed. All core parsers, API connectivity, and workspace health states are reported above.")
		default:
			sb.WriteString(fmt.Sprintf("Completed action `%s`.", tr.Name))
		}
		sb.WriteString("\n\n")
	}

	return strings.TrimSpace(sb.String())
}

func (e *Engine) generateHumanOfflineResponse(userPrompt string) string {
	p := strings.ToLower(strings.TrimSpace(userPrompt))

	existingLocales := []string{}
	if e.Platform != nil {
		if locMap, err := e.Platform.DiscoverExistingLocales(e.ProjectRoot); err == nil {
			for loc := range locMap {
				existingLocales = append(existingLocales, loc)
			}
		}
	}

	// 1. Greetings
	if p == "hey" || p == "hi" || p == "hello" || p == "yo" || p == "hey buddy" || strings.HasPrefix(p, "hey ") || strings.HasPrefix(p, "hello ") {
		return fmt.Sprintf("Hey. I am your **langPeanut Copilot**, ready to help you with localization and code refactoring for **%s** (%s).\n\nWhat would you like to work on? You can ask me to:\n- **\"Scan my repository\"** to find all hardcoded UI strings\n- **\"Translate missing keys into %s\"**\n- **\"Run 4-tier verification critic\"** to test ICU safety\n- **\"Simulate Google SERP rankings\"** for global markets\n- **\"Check repo settings or missing items\"** to audit setup readiness",
			filepath.Base(e.ProjectRoot),
			e.Platform.DisplayName(),
			strings.Join(e.TargetLocales, ", "),
		)
	}

	// 2. Data & Status & Missing Config Queries
	if strings.Contains(p, "data") || strings.Contains(p, "what do you have") || strings.Contains(p, "status") || strings.Contains(p, "summary") || strings.Contains(p, "what do you know") || strings.Contains(p, "settings") || strings.Contains(p, "missing") {
		var sb strings.Builder
		repoName := filepath.Base(e.ProjectRoot)
		if e.RepoMetadata != nil && e.RepoMetadata["full_name"] != nil {
			repoName = fmt.Sprintf("%v", e.RepoMetadata["full_name"])
		}
		sb.WriteString(fmt.Sprintf("### Repository Configuration & Status for `%s`\n\n", repoName))
		sb.WriteString(fmt.Sprintf("- **Detected Framework**: `%s`\n", e.Platform.DisplayName()))
		sb.WriteString(fmt.Sprintf("- **Discovered Hardcoded Strings**: `%d` candidates in AST\n", len(e.Candidates)))
		sb.WriteString(fmt.Sprintf("- **Target Locales**: `%v`\n", e.TargetLocales))
		if len(existingLocales) > 0 {
			sb.WriteString(fmt.Sprintf("- **Existing Locale Files**: `%v`\n", existingLocales))
		}
		sb.WriteString(fmt.Sprintf("- **Tone Preset**: `%s`\n", e.ToneStyle))

		if len(e.RepoMetadata) > 0 {
			if prov, ok := e.RepoMetadata["provider"].(string); ok && prov != "" {
				sb.WriteString(fmt.Sprintf("- **Active Provider**: `%s` (Model: `%v`)\n", prov, e.RepoMetadata["model"]))
			}
			if hasKey, ok := e.RepoMetadata["has_api_key"].(bool); ok {
				if hasKey {
					sb.WriteString("- **API Key Configured**: Yes (Vault / Override ready)\n")
				} else {
					sb.WriteString("- **API Key Configured**: No (Key missing for active provider)\n")
				}
			}
			if dir, ok := e.RepoMetadata["user_directive"].(string); ok && dir != "" {
				sb.WriteString(fmt.Sprintf("- **Custom Developer Directive**: *\"%s\"*\n", dir))
			}
		}

		if len(e.MissingConfig) > 0 {
			sb.WriteString("\n### Configuration Gaps & Action Items\n")
			for _, m := range e.MissingConfig {
				sb.WriteString(fmt.Sprintf("- %s\n", m))
			}
		} else {
			sb.WriteString("\n**All required repository configuration items are in order and ready for execution.**\n")
		}

		sb.WriteString("\nWould you like me to **run an AST scan**, **trigger a background job**, or **adjust settings**?")
		return sb.String()
	}

	// 3. Identity / Capabilities
	if strings.Contains(p, "who are you") || strings.Contains(p, "what can you do") || strings.Contains(p, "what are you") || strings.Contains(p, "help") {
		return fmt.Sprintf("I am **langPeanut Copilot**, your autonomous AI pair-programmer for internationalization and localization.\n\nHere is how I can assist you:\n1. **Zero-Defect AST Refactoring**: I parse your source code using Tree-sitter, identify hardcoded UI strings, and apply byte-range replacements without breaking syntax.\n2. **ICU & Plural Safety**: I ensure variable placeholders (`{userName}`, `{count}`) are 100%% protected during translation.\n3. **4-Tier Critic Quality Gate**: I verify syntax, ICU token alignment, layout expansion risk, and key parity.\n4. **Global SEO Simulation**: I generate Google SERP search result previews and weave high-intent local keywords into your localized copy.\n5. **Platform Job Execution**: I trigger background translation runs on any branch, manage checkpoints, and report setup gaps.\n\nTell me what you would like to do, or try asking: *\"What is missing in my repository setup?\"*")
	}

	// 4. Fallback contextual response
	return fmt.Sprintf("I understand. You asked: *\"%s\"*.\n\nI am connected to your **%s** codebase (`%s`) with **%d** hardcoded strings tracked. To have me execute actions, ask me to **scan the repository**, **translate missing keys to %s**, **run the 4-tier critic**, or **check what info is missing**.",
		userPrompt,
		e.Platform.DisplayName(),
		filepath.Base(e.ProjectRoot),
		len(e.Candidates),
		strings.Join(e.TargetLocales, ", "),
	)
}

func (e *Engine) GetHistory() []ChatMessage {
	e.mu.RLock()
	defer e.mu.RUnlock()
	return e.History
}

func (e *Engine) ResetHistory() {
	e.mu.Lock()
	defer e.mu.Unlock()
	e.History = make([]ChatMessage, 0)
}

func extractLocalesFromPrompt(p string) []string {
	var locales []string
	known := map[string]string{
		"spanish": "es", "es": "es",
		"french": "fr", "fr": "fr",
		"german": "de", "de": "de",
		"japanese": "ja", "ja": "ja",
		"chinese": "zh", "zh": "zh",
		"korean": "ko", "ko": "ko",
		"italian": "it", "it": "it",
		"portuguese": "pt", "pt": "pt",
		"russian": "ru", "ru": "ru",
		"arabic": "ar", "ar": "ar",
		"hindi": "hi", "hi": "hi",
	}

	words := strings.Fields(strings.ToLower(p))
	seen := make(map[string]bool)
	for _, w := range words {
		w = strings.Trim(w, ",.;:!?\"'()[]")
		if code, ok := known[w]; ok {
			if !seen[code] {
				seen[code] = true
				locales = append(locales, code)
			}
		}
	}
	return locales
}

func generateID(prefix string) string {
	b := make([]byte, 8)
	_, _ = rand.Read(b)
	return fmt.Sprintf("%s_%s_%d", prefix, hex.EncodeToString(b), time.Now().UnixNano()%1000000)
}

func emitEvent(ch chan<- ChatEvent, ev ChatEvent) {
	if ch == nil {
		return
	}
	select {
	case ch <- ev:
	default:
	}
}
